#!/bin/sh
# runit-vm
# Copyright (c) 2020 Jovan Lanik
#

# Find and source config file. Location can be overwritten with $VMCONF, otherwise look in $XDG_CONFIG_HOME and ~/.config
if test -z "$VMCONF"
then
	VMCONF="/etc/runit-vm/conf"
	if test "$(id -u)" -ne 0
	then
		[ -e "$HOME/.config/runit-vm/conf" ] && VMCONF="$HOME/.config/runit-vm/conf"
		[ -e "$XDG_CONFIG_HOME/runit-vm/conf" ] && VMCONF="$XDG_CONFIG_HOME/runit-vm/conf"
	fi
fi
[ -r "$VMCONF" ] && . $VMCONF
# If any option is missing in environment or config set default value
[ -z "$VMCONF_DEFAULT_TEMPLATES"] && VMCONF_DEFAULT_TEMPLATES="audio-pa cpu-host drive kvm mem"
[ -z "$VMDIR" ] && VMDIR="$HOME/.local/vms"

# Check if $VMDIR is valid
[ ! -d "$VMDIR/default" ] && echo "vm: no default vm in $VMDIR" && exit 1

case $1 in
	'list')
		[ "$#" -ne 1 ] && echo "vm: arguments wrong. See 'vm help'" && exit 1
		ls $VMDIR | grep -v 'default'
		;;
	'make')
		[ "$#" -lt 2 ] || [ "$#" -gt 3 ] && echo "vm: arguments wrong. See 'vm help'" && exit 1
		[ -d "$VMDIR/$2" ] && echo "vm: vm named $2 already exists" && exit 1

		mkdir "$VMDIR/$2"
		cd "$VMDIR/$2"

		touch ./down
		printf "Disk image size for $2? "; read ANS
		qemu-img create -f qcow2 ./drive.qcow2 "${ANS:=${VMCONF_DEFAULT_DRIVE:='20G'}}"

		echo; printf "Safe poweroff wait time for $2? "; read ANS
		echo "${ANS:=${VMCONF_DEFAULT_WAIT:='10'}}" > ./wait

		echo; printf "\nLog $2? [y/N] "; read ANS
		[ "$ANS" != "${ANS#[Yy]}" ] && ln -s ../default/log ./

		mkdir ./templates
		echo
		echo "Default templates:"; echo $VMCONF_DEFAULT_TEMPLATES
		echo "Available templates:"; ls ../default/templates/
		printf "Templates for $2? "; read ANS
		for i in $VMCONF_DEFAULT_TEMPLATES $ANS
		do
			rm -f "./templates/$(echo $i | cut -d '-' -f 1)"*
			cp "../default/templates/$i" ./templates/
		done
		[ -n "$3" ] && [ -e "$3" ] && echo "-cdrom '$(realpath $3)' -boot order=d" > ./templates/once

		ln -s ../default/run ./
		SVDIR=$VMDIR sv once $2
		;;
	'boot')
		[ "$#" -lt 2 ] && echo "vm: arguments wrong. See 'vm help'" && exit 1
		for i in $(seq 3 $#)
		do
			eval NEW=\"\$\{$i\}\"
			ARG="$ARG $NEW"
		done
		echo $ARG >> "$VMDIR/$2/templates/once"
		SVDIR=$VMDIR sv once $2
		;; 
	'sv')
		for i in $(seq 2 $#)
		do
			eval NEW=\"\$\{$i\}\"
			ARG="$ARG $NEW"
		done
		SVDIR=$VMDIR sv $ARG
		;;
	'help')
		[ "$#" -ne 1 ] && echo "vm: arguments wrong. See 'vm help'" && exit 1
		echo 'runit-vm - QEMU wrapper using runit to manage vms'
		echo 'usage:'
		echo '	vm <command> [<args>]'
		echo 'commands:'
		echo '	list - list all vms in $VMDIR'
		echo '	make <vm> [<iso>] - interactively create new vm'
		echo '	boot <vm> [<arg>] - boot vm and pass args to qemu'
		echo '	sv <command> <vms> - directly control runsv'
		echo '	help - display this help'
		echo 'environment:'
		echo '	VMCONF - sourced by vm, any environment variables can be overwritten here'
		echo '		defaults to $XDG_CONFIG_HOME/runit-vm/conf then ~/.config/runit-vm/conf and finally /etc/runit-vm/conf' 
		echo '	VMDIR - defaults to ~/.local/vms'
		echo '	VMCONF_DEFAULT_TEMPLATES, VMCONF_DEFAULT_DRIVE, VMCONF_DEFAULT_WAIT'
		;;
	'')
		echo "vm: no command. See 'vm help'"
		;;
	*)
		echo "vm: $1 is not a vm command. See 'vm help'"
		;;
esac
