#!/bin/sh
if [ -z "$VMCONF" ]
then
	VMCONF="/etc/runit-vm/conf"
	if [ "$(id -u)" -ne 0 ]
	then
		[ -e "$HOME/.config/runit-vm/conf" ] && VMCONF="$HOME/.config/runit-vm/conf"
		[ -e "$XDG_CONFIG_HOME/runit-vm/conf" ] && VMCONF="$XDG_CONFIG_HOME/runit-vm/conf"
	fi
fi
[ -r "$VMCONF" ] && . "$VMCONF"
[ -z "$VMDIR" ] && VMDIR="$HOME/.local/share/runit-vm"
exec runsvdir "$VMDIR"
